# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190714_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_klimat',
            name='curah_hujan',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='kec_rata_angin',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='kelembaban',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='penyinaran_matahari',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='tekanan_udara',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='temp_max',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='temp_min',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='temp_rata2',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
