# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190714_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_klimat',
            name='bulan',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='curah_hujan',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='kec_rata_angin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='kelembaban',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='penyinaran_matahari',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='tekanan_udara',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='temp_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='temp_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data_klimat',
            name='temp_rata2',
            field=models.FloatField(null=True),
        ),
    ]
