# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190714_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_klimat',
            name='bulan',
            field=models.CharField(max_length=40),
        ),
    ]
