# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20190714_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_klimat',
            name='kec_rata_angin1',
            field=models.FloatField(null=True),
        ),
    ]
