# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_data_klimat_kec_rata_angin1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_klimat',
            name='kec_rata_angin1',
        ),
    ]
