# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_indeks_musiman'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_klimat',
            name='tahun',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
